package gitctx

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestPathReason(t *testing.T) {
	for path, want := range map[string]string{
		"go.sum":                               ReasonLockfile,
		"web/package-lock.json":                ReasonLockfile,
		"Cargo.lock":                           ReasonLockfile,
		"static/app.min.js":                    ReasonMinified,
		"static/app.js.map":                    ReasonMinified,
		"ui/__snapshots__/Button.test.js.snap": ReasonSnapshot,
		"ui/__snapshots__/notes.txt":           ReasonSnapshot,
		"main.go":                              "",
		"lock.go":                              "",
		"docs/go.sum.md":                       "",
	} {
		if got := pathReason(path); got != want {
			t.Errorf("pathReason(%q) = %q, want %q", path, got, want)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	for _, tc := range []struct {
		name string
		head string
		want bool
	}{
		{"protoc", "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: api.proto\npackage api\n", true},
		{"stringer", "// Code generated by \"stringer -type=Kind\"; DO NOT EDIT.\n\npackage k\n", true},
		{"@generated", "/**\n * @generated by relay-compiler\n */\nexport default {}\n", true},
		{"python", "# Code generated by tool; DO NOT EDIT.\nx = 1\n", true},
		{"hand-written", "package main\n\nfunc main() {}\n", false},
		{"phrase in code, not a comment", "msg := \"Code generated, DO NOT EDIT\"\n", false},
		{"marker too far down", strings.Repeat("// header\n", headerLines) + "// Code generated. DO NOT EDIT.\n", false},
		{"undecorated lines in a block comment", "/*\nCode generated by tool. DO NOT EDIT.\n*/\npackage p\n", true},
		{"html block comment", "<!--\n  @generated by docs tool\n-->\n<html>\n", true},
		{"code after a closed block", "/* license */\nconst s = \"Code generated, DO NOT EDIT\"\n", false},
		{"marker in code after a closer on the same line", "/* header */ const label = \"@generated\";\n", false},
		{"marker on a later line, after code", "/* header */ x();\n// @generated\n", false},
		{"one-line block comment banner", "/* @generated */\npackage p\n", true},
		{"banner inside a raw string", "package tmpl\n\nconst t = `\n// Code generated by tool. DO NOT EDIT.\n`\n", false},
		{"after a blank line and a license", "\n// Copyright 2026\n\n// Code generated by x. DO NOT EDIT.\npackage p\n", true},
	} {
		if got := isGenerated(tc.head); got != tc.want {
			t.Errorf("%s: isGenerated = %v, want %v", tc.name, got, tc.want)
		}
	}
}

const (
	modifiedSection = "diff --git a/main.go b/main.go\nindex 1..2 100644\n--- a/main.go\n+++ b/main.go\n@@ -10,2 +10,2 @@\n x := 1\n-y := 2\n+y := 3\n"
	lockSection     = "diff --git a/go.sum b/go.sum\n--- a/go.sum\n+++ b/go.sum\n@@ -1 +1 @@\n-a v1 h1:x\n+a v2 h1:y\n"
	deletedSection  = "diff --git a/old.go b/old.go\ndeleted file mode 100644\nindex 1..0\n--- a/old.go\n+++ /dev/null\n@@ -1,2 +0,0 @@\n-package old\n-func F() {}\n"
	renameSection   = "diff --git a/a.go b/b.go\nsimilarity index 100%\nrename from a.go\nrename to b.go\n"
	binarySection   = "diff --git a/logo.png b/logo.png\nindex 1..2 100644\nBinary files a/logo.png and b/logo.png differ\n"
	newGenSection   = "diff --git a/api.pb.go b/api.pb.go\nnew file mode 100644\n--- /dev/null\n+++ b/api.pb.go\n@@ -0,0 +1,2 @@\n+// Code generated by protoc-gen-go. DO NOT EDIT.\n+package api\n"
	editGenSection  = "diff --git a/kind_string.go b/kind_string.go\n--- a/kind_string.go\n+++ b/kind_string.go\n@@ -20,1 +20,1 @@\n-const _Kind_name = \"AB\"\n+const _Kind_name = \"ABC\"\n"
)

func excludedReasons(ex []Excluded) map[string]string {
	out := map[string]string{}
	for _, e := range ex {
		out[e.Path] = e.Reason
	}
	return out
}

func TestAutoExclude(t *testing.T) {
	diff := modifiedSection + lockSection + deletedSection + renameSection + binarySection + newGenSection + editGenSection
	heads := func(paths []string) map[string]string {
		if !slices.Equal(paths, []string{"main.go", "kind_string.go"}) {
			t.Errorf("heads asked for %v, want only the files whose top the diff does not show", paths)
		}
		return map[string]string{
			"main.go":        "package main\n",
			"kind_string.go": "// Code generated by \"stringer -type=Kind\"; DO NOT EDIT.\n",
		}
	}
	kept, excluded := autoExclude(diff, heads)
	if kept != modifiedSection {
		t.Errorf("kept:\n%s\nwant only main.go", kept)
	}
	want := map[string]string{
		"go.sum":         ReasonLockfile,
		"old.go":         ReasonDeleted,
		"b.go":           ReasonNoText,
		"logo.png":       ReasonNoText,
		"api.pb.go":      ReasonGenerated,
		"kind_string.go": ReasonGenerated,
	}
	got := excludedReasons(excluded)
	if len(got) != len(want) {
		t.Errorf("excluded = %v, want %v", got, want)
	}
	for p, r := range want {
		if got[p] != r {
			t.Errorf("%s: reason %q, want %q", p, got[p], r)
		}
	}

	// A hunk at the top that shows only a few lines settles nothing without
	// the marker: the header is read, and the marker on line 7 found.
	short := "diff --git a/k.go b/k.go\n--- a/k.go\n+++ b/k.go\n@@ -1,3 +1,3 @@\n-// Old header\n+// New header\n // more\n // more\n"
	marked := strings.Repeat("// x\n", 6) + "// Code generated by tool. DO NOT EDIT.\n"
	_, ex := autoExclude(short, func([]string) map[string]string { return map[string]string{"k.go": marked} })
	if len(ex) != 1 || ex[0].Reason != ReasonGenerated {
		t.Errorf("short top hunk: excluded = %v, want k.go as generated from its header", ex)
	}

	// Without a way to read files, a generated file the diff only shows
	// mid-file is kept: it cannot be recognised.
	if kept, _ := autoExclude(editGenSection, nil); kept != editGenSection {
		t.Error("with no heads, an edit inside a generated file should be kept")
	}
}

func gitIn(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GIT_AUTHOR_NAME=t", "GIT_AUTHOR_EMAIL=t@t", "GIT_COMMITTER_NAME=t", "GIT_COMMITTER_EMAIL=t@t")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
}

func writeIn(t *testing.T, dir, name, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// Heads come from the index for staged changes, with one git cat-file for
// every file; a path git does not have is left out.
func TestRevisionHeads(t *testing.T) {
	dir := t.TempDir()
	gitIn(t, dir, "init", "-q")
	writeIn(t, dir, "gen.go", "// Code generated by x. DO NOT EDIT.\npackage gen\n")
	writeIn(t, dir, "big.txt", strings.Repeat("y", headBytes*2))
	gitIn(t, dir, "add", ".")
	writeIn(t, dir, "gen.go", "package handwritten\n") // unstaged: the index still has the generated one

	got := revisionHeads(context.Background(), dir, "")([]string{"missing file.go", "gen.go", "missing.go", "big.txt"})
	if !isGenerated(got["gen.go"]) {
		t.Errorf("gen.go head = %q, want the staged, generated content", got["gen.go"])
	}
	if _, ok := got["missing.go"]; ok {
		t.Error("a missing path should have no head")
	}
	if len(got["big.txt"]) != headBytes {
		t.Errorf("big.txt head is %d bytes, want %d", len(got["big.txt"]), headBytes)
	}
}

// buildResult records what it left out, drops it from Files, and leaves
// everything in with NoAutoExclude.
func TestBuildResult_AutoExclude(t *testing.T) {
	diff := modifiedSection + lockSection
	got, err := buildResult(context.Background(), diff, "snippet", "", DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if got.Diff != modifiedSection || !slices.Equal(got.Files, []string{"main.go"}) || len(got.Excluded) != 1 || got.Excluded[0].Path != "go.sum" {
		t.Errorf("diff kept go.sum or files/excluded wrong: files %v, excluded %v", got.Files, got.Excluded)
	}
	all, err := buildResult(context.Background(), diff, "snippet", "", DiffOptions{NoAutoExclude: true})
	if err != nil {
		t.Fatal(err)
	}
	if all.Diff != diff || len(all.Excluded) != 0 {
		t.Errorf("NoAutoExclude: excluded %v", all.Excluded)
	}
}

// Codebase mode leaves out lockfiles by name and generated files by their
// header, and says so.
func TestCodebase_AutoExclude(t *testing.T) {
	dir := t.TempDir()
	gitIn(t, dir, "init", "-q")
	writeIn(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	writeIn(t, dir, "go.sum", "a v1 h1:x\n")
	writeIn(t, dir, "api/api.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n")
	gitIn(t, dir, "add", ".")
	gitIn(t, dir, "commit", "-q", "-m", "init")
	t.Chdir(dir)

	got, err := Codebase(context.Background(), DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(got.Files, []string{"main.go"}) {
		t.Errorf("files = %v, want only main.go", got.Files)
	}
	if r := excludedReasons(got.Excluded); r["go.sum"] != ReasonLockfile || r["api/api.pb.go"] != ReasonGenerated {
		t.Errorf("excluded = %v", got.Excluded)
	}
}

// Git quotes header paths with unusual characters; they are decoded.
func TestHeaderPath(t *testing.T) {
	for _, tc := range []struct {
		header       string
		old, renamed string
	}{
		{"diff --git a/main.go b/main.go\n", "main.go", "main.go"},
		{"diff --git a/a.go b/b.go\n", "a.go", "b.go"},
		{"diff --git \"a/caf\\303\\251.go\" \"b/caf\\303\\251.go\"\n", "café.go", "café.go"},
		{"diff --git \"a/tab\\there.go\" b/plain.go\n", "tab\there.go", "plain.go"},
		{"diff --git a/old name.go \"b/new\\tname.go\"\n", "old name.go", "new\tname.go"},
		// A path containing " b/": the header alone is ambiguous.
		{"diff --git a/foo b/bar b/foo b/bar\nBinary files a/foo b/bar and b/foo b/bar differ\n", "foo b/bar", "foo b/bar"},
		{"diff --git a/foo b/bar b/foo b/bar\ndeleted file mode 100644\n--- a/foo b/bar\n+++ /dev/null\n", "foo b/bar", "foo b/bar"},
		{"diff --git a/x b/y b/z\nsimilarity index 100%\nrename from x b/y\nrename to z\n", "x b/y", "z"},
		{"diff --git a/q.go b/q.go\n--- \"a/caf\\303\\251.go\"\n+++ \"b/caf\\303\\251.go\"\n", "café.go", "café.go"},
		// Git's trailing tab after a path with spaces is not part of it.
		{"diff --git a/hello world.go b/hello world.go\ndeleted file mode 100644\n--- a/hello world.go\t\n+++ /dev/null\n", "hello world.go", "hello world.go"},
		// A real b/ directory inside a quoted path survives.
		{"diff --git a/q b/q\n--- \"a/b/file\\t.go\"\n+++ \"b/b/file\\t.go\"\n", "b/file\t.go", "b/file\t.go"},
		{"diff --git a/q b/r\nrename from \"b/old\\t.go\"\nrename to \"a/new\\t.go\"\n", "b/old\t.go", "a/new\t.go"},
		{"diff --git \"a/new\\tname.go\" b/spaced name.go\n", "new\tname.go", "spaced name.go"},
	} {
		if got := headerPath(tc.header, false); got != tc.old {
			t.Errorf("%q: old path %q, want %q", tc.header, got, tc.old)
		}
		if got := headerPath(tc.header, true); got != tc.renamed {
			t.Errorf("%q: new path %q, want %q", tc.header, got, tc.renamed)
		}
	}
}

// A symlink's target is not read: git reviews the link, not what it points at.
func TestWorkingTreeHeads_SkipsSymlinks(t *testing.T) {
	dir := t.TempDir()
	writeIn(t, dir, "gen.go", "// Code generated by x. DO NOT EDIT.\n")
	if err := os.Symlink(filepath.Join(dir, "gen.go"), filepath.Join(dir, "link.go")); err != nil {
		t.Skip("symlinks not supported:", err)
	}
	got := workingTreeHeads(dir)([]string{"gen.go", "link.go"})
	if _, ok := got["link.go"]; ok || got["gen.go"] == "" {
		t.Errorf("heads = %v, want gen.go read and link.go skipped", got)
	}
}

// Markers in a hunk's content are code, not metadata: a line whose text
// makes it look like "+++ /dev/null" in the diff does not make the file a
// deletion.
func TestAutoExclude_MarkersInContent(t *testing.T) {
	sec := "diff --git a/n.txt b/n.txt\n--- a/n.txt\n+++ b/n.txt\n@@ -1,1 +1,2 @@\n keep\n+++ /dev/null\n"
	if kept, ex := autoExclude(sec, nil); kept != sec || len(ex) != 0 {
		t.Errorf("an added line spelling a deletion marker excluded the file: %v", ex)
	}
}

func TestParentRangeTip(t *testing.T) {
	for in, want := range map[string]string{"HEAD^!": "HEAD", "abc123^-": "abc123", "v1.2^-2": "v1.2"} {
		if got, ok := parentRangeTip(in); !ok || got != want {
			t.Errorf("parentRangeTip(%q) = %q, %v; want %q", in, got, ok, want)
		}
	}
	for _, in := range []string{"HEAD", "HEAD~3", "^!", "a^-x"} {
		if _, ok := parentRangeTip(in); ok {
			t.Errorf("parentRangeTip(%q) should not be a parent range", in)
		}
	}
}
